@startuml
title "Cas d'usages - Bibliothèque Numérique (Lecteur)"
left to right direction
actor Lecteur as reader <<Utilisateur>>
node "Système d'inventaire" as InventorySystem
rectangle "Scenario d'un lecteur" {
  usecase "Consulter le catalogue" as ReadCatalogUsecase
  usecase "Emprunter un livre" as BorrowBookUsecase
  usecase "Retourner un livre" as ReturnBookUsecase
  usecase "Voir mes emprunts en cours" as ViewCurrentLoansUsecase
  usecase "Vérifier disponibilité du livre" as CheckAvailabilityUsecase
  reader --> ReadCatalogUsecase
  reader --> BorrowBookUsecase
  reader --> ReturnBookUsecase
  reader --> ViewCurrentLoansUsecase
  ReadCatalogUsecase <.. CheckAvailabilityUsecase : <<extend>>
  CheckAvailabilityUsecase --> InventorySystem
  BorrowBookUsecase ..> CheckAvailabilityUsecase : <<include>>
}
note bottom of CheckAvailabilityUsecase : Le livre doit avoir au moins\nun exemplaire disponible.
@enduml